name = "erp-laplata"
compatibility_date = "2024-01-01"

[env.production]
name = "erp-laplata"

[[env.production.pages_builds]]
command = "cd frontend && npm install && npm run build"
cwd = "frontend"
watch_dir = "frontend"

[env.production.vars]
NEXT_PUBLIC_APP_NAME = "ERP Laplata"